describe('question page', () => {
    beforeEach(() => {
        cy.visit('localhost:3000/quiz')
    })
    it('should contain 5 sliders', () => {
        cy.get('#size')
        cy.get('#familyRating')
        cy.get('#trainability')
        cy.get('#groomingNeeded')
        cy.get('#energyLevel')
    })
    it('should be able to change slider values', () => {
        cy.get('input[type=range]').eq(0)
            .invoke('val', '5')
            .trigger('change')
    })
    it('should be able to change all slider values', () => {
        cy.get('input[type=range]').eq(0)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(1)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(2)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(3)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(4)
            .invoke('val', '5')
            .trigger('change')
    })
    it('should be able to submit', () => {
        cy.get('input[type=range]').eq(0)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(1)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(2)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(3)
            .invoke('val', '5')
            .trigger('change')
        cy.get('input[type=range]').eq(4)
            .invoke('val', '5')
            .trigger('change')
        cy.get('button').click()
    })
})